### ISSUE TITLE
error 500 on installing

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/faqfield#1]
On backdrop 1.20.0, I have a 500 error when installing through project installer. This is the logged error message:

```
Error: Call to undefined function user_access() a _color_preview_theme() (línia 471 de /(...)/core/modules/color/color.module).
```

**Comment by robertgarrigos** [comment]
Fixed by turning off the core's color module (????)

**Comment by robertgarrigos** [comment]
But then got css errors (I guess because of javascript incompatibility).

**Comment by alanmels** [comment]
Thanks for reporting. Unfortunately, AltaGrade team has been - and apparently will be for several more months - quite busy with a large Drupal project, so we don't have time to look into this. I could accept PR though if you find a culprit. 

For the time being, I'd recommend to use Paragraphs (and Paragraphs jQuery UI Accordion) instead. That's how https://www.nyexpress.us/faq was built, for example.

**Comment by metatop** [comment]
Same problem, they should disable the module until the problem is solved. It has caused me headaches to get the site online again.
