### ISSUE TITLE
FAQ field doesn't save Default value

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/faqfield#4]
When you add a default value to a FAQ field, it doesn't get saved.

**Steps to reproduce:**

1. Add a FAQ field to a content type, or use an existing FAQ field.
2. Change the default value of the question and / or the answer.
3. Save the settings.
4. Configure the field again, and look at the default value.

Actual behavior: The default value is empty.

Expected behavior: There is a default value, e.g. a default answer.

**Comment by olafgrabienski** [comment]
I have noticed the issue for the first time, when I tried to change the Default value's text format for the "Formattable textarea" answer widget. Note to myself: Test a possible fix also for this use case.

**Comment by alanmels** [comment]
For future references, the [git blame](https://github.com/backdrop-contrib/faqfield/blame/f0f2741f848b4b9485c54f2967468ec6ac76f548/faqfield.module#L482) of the deleted [line 486](https://github.com/backdrop-contrib/faqfield/blame/f0f2741f848b4b9485c54f2967468ec6ac76f548/faqfield.module#L482) `$form_state['values'][$field['field_name']] = NULL;` references https://www.drupal.org/node/1526448, but I don't see Drupal's issue on Backdrop, so we should be safe.
