### ISSUE TITLE
Answer widget conflict: Formattable textarea vs. Paragraphs

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/faqfield#5]
I'm trying to use a FAQ Field in Paragraphs. In the field configuration I've set the Answer widget to "Formattable textarea". This works fine at first sight, I can create a FAQ section. However, when I edit the FAQs again, the content in the edit form seems to be removed. Instead of my content, I see the term "Array" in the editor (see screenshot below).

In the DBlog, I see the following notice:

> Array to string conversion in check_plain() (line 2089 of my-path-to/core/includes/bootstrap.inc).

There is no issue when I change the Answer widget to "Textarea".

---

**Answer widget is Formattable textarea: "Array" instead of content**
<img src="https://github.com/backdrop-contrib/faqfield/assets/14188307/be300308-724b-4395-bae2-0bc52647bd56" width="600">

**Answer widget is Textarea: content is there**
<img src="https://github.com/backdrop-contrib/faqfield/assets/14188307/d6eeae0e-6430-48f0-a747-6159166ba912" width="600">

**Comment by olafgrabienski** [comment]
I've noticed there is no issue when I change the 'Default edit mode' of Paragraphs to "Open". So, there seems to be a conflict between the FAQ Field "Formattable textarea" and the 'Default edit modes' "Closed" and "Preview" from Paragraphs.

I'm not sure if this is a FAQ Field or a Paragraphs issue, so I have filed this report here also [in the Paragraphs queue](https://github.com/backdrop-contrib/paragraphs/issues/182).

**Comment by alanmels** [comment]
Since you are using Paragraphs, have you considered using [Paragraphs jQuery UI Accordion](https://github.com/backdrop-contrib/paragraphs_jquery_ui_accordion)? That's what we do whenever we use Paragraphs (see, for example, https://www.homiebees.com/#faq).

**Comment by olafgrabienski** [comment]
@alanmels Thanks for your suggestion. I had considered _Paragraphs jQuery UI Accordion_, but I think, _FAQ Field_ is a better fit for my approach.

Using _Paragraphs jQuery UI Accordion_, you have to set the Accordion format in the _Manage display_ screen for your Paragraphs field, e.g. in a page content type. This way, you can't really use the same Paragraphs field with other Paragraph types. In contrast, _FAQ Field_ defines the Accordion format on the Paragraphs type level. This is much more flexible, in my opinion.

So, I guess I'm still interested to get FAQ Field running for my use case.

**Comment by laryn** [comment]
@olafgrabienski @alanmels I think this is due to legacy code in FAQ Field.

 - https://github.com/backdrop-contrib/faqfield/blob/1.x-1.x/faqfield.module#L438-L448

The error control operators in use are not recommended to my knowledge (e.g. `@$items[$delta]['question']`) but in this case, it seems the logic above isn't flexible enough for the case where a formatted textarea returns an array with keys for both `value` and `format`. It should maybe be broken apart or somehow checking if it's an array in this section.

**Comment by laryn** [comment]
Maybe related: https://www.drupal.org/project/faqfield/issues/2665278

**Comment by alanmels** [comment]
@olafgrabienski and @laryn, thanks for the updates on the issue. Unfortunately, no time to investigate and tackle this for now, but I'd love to commit any PR.
