### ISSUE TITLE
TypeError when editing FAQ field content

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/faqfield#6]
Testing the [current release 1.0.2](https://github.com/backdrop-contrib/faqfield/releases/tag/1.x-1.0.2), I've encountered an issue when editing FAQ field content.

**Steps to reproduce:**

1. Add a FAQ field to a content type.
2. Keep the default settings.
3. Add a content item, put something in the FAQ field, and save the item.
4. Try to edit the content item.
 
Result: You see a blank page with the message "Cannot access offset of type string on string".

The whole message in DBlog:

> TypeError: Cannot access offset of type string on string in faqfield_field_widget_form() (line 442 of modules/faqfield/faqfield.module).

**Comment by olafgrabienski** [comment]
I've edited the steps in the issue description (added step 2).

**Comment by laryn** [comment]
The patch in the issue I linked in the other thread may be useful:

https://www.drupal.org/files/issues/faq-display-default-values-using-paragraph-module-4.patch

**Comment by olafgrabienski** [comment]
I've edited the issue description again and changed the title as well. The issue looks quite serious, as it appears not only with default field values but generally when editing FAQ field content.

**Comment by alanmels** [comment]
Thanks for letting me know. I'll take a look at this later today.

**Comment by olafgrabienski** [comment]
Thanks for the fix, @alanmels! Tested it only now, and it works for me.
